### ISSUE TITLE
Feature request: Add option to load Fire IE plugin inside plugin-container.exe instead of firefox.exe

### ISSUE THREAD

**Issue by pal1000** [yxl/Fire-IE#107] opened 2013-08-20 13:03 UTC
Fire IE should load, if possible the plugin (npfireie32.dll / npfireie64.dll) in plugin-container.exe instead of firefox.exe. If it can be implemented the user should have an option to choose between these 2 operation modes. Each operation mode has advantages and disadvantages. For instance, loading the plugin in plugin-container.exe allows:
-the user to stop plugin execution if it becomes unresponsive (firefox unresponsive plugin dialog would pop-up at some point);
-firefox usability even if npfireie(32/64).dll crashes.
As a disadvantage this implementation might reduce plugin stability (it happened with IE Tab V2).
The current implementation of Fire IE is very stable, unfortunately there are cases when Internet Explorer crashes or hang unavoidably due to buggy ActiveX controls or buggy applications called on to execute by ActiveX controls (issues that occur on the real IE, not the embedded one through Fire IE). A known example is SopCast which under certain conditions when loading certain channels causes Internet Explorer to hang. The same thing happens in Firefox through Fire IE (permanent hang); the only solution being Firefox termination. To proof that the issue is not at browser(s) level, but rather at SopCast application level: by grabbing the Sop URL of the playing channel from source of webpage and imputing it into the SopCast application would surely cause SopCast to hang when loading the channel. If implemented, loading the plugin in plugin-container.exe would allow the user to stop the plugin and unfreeze Firefox.
So, please take this in consideration, or if you already taken it to begin with just tell me that it's impossible due to plugin implementation to support so many features unlike any other IE embedding plugin.

**Comment by patwonder** [comment] 2015-01-23 14:57
Closing this issue as a duplicate of #65.

As of a75e80c476fb07a8e85f90f12f9829ab993d6791, OOPP mode is quite stable. It will be enabled by default along with e10s (multiprocess firefox) support. See the e10s tracking issue here: #128.

**Closed by patwonder** 2015-01-23 14:57 UTC
Labels: Duplicate, Feature

**Comment by pal1000** [comment] 2015-01-24 13:22
This doesn't help me much if Adblock Plus integration doesn't work.

**Comment by patwonder** [comment] 2015-01-24 13:24
@pal1000 Adblock Plus integration works in OOPP mode and should work in e10s, too.
